services:
  php-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: php-app
    restart: unless-stopped
    init: true
    # env_file: ./.env  # Uncomment if .env file exists
    depends_on:
      - mysql-db
    networks:
      - backend
    expose:
      - "9000"  # php-fpm default port
    # If you want to serve via web server (nginx/apache), add a web service and link here

  java-android:
    build:
      context: ./android
      dockerfile: ../androidDockerfile
    container_name: java-android
    restart: unless-stopped
    init: true
    networks:
      - backend
    expose:
      - "8080"  # Default port for Java apps
    # env_file: ./android/.env  # Uncomment if .env file exists in android/

  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Change this in production!
      MYSQL_DATABASE: dbedcerp
      MYSQL_USER: erpuser
      MYSQL_PASSWORD: erppassword
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  backend:
    driver: bridge

volumes:
  mysql-data:
    # Persistent storage for MySQL database
